#### This file generates two files:
* action_frequency: each row in the table represents a time a user like/dislike/wishlist.
* action_watchmorethanhalf: each row in the table represents a time when a user watches more than half of a trailer

In [1]:
import pandas as pd
import numpy as np

In [2]:
action_data_raw = pd.read_csv('../Clean_Data/log_trailer_actions_sessionIds.csv')

In [3]:
# Get the algorithm assignment
expt_trailer = pd.read_csv('../Data/expt_trailer.csv', sep=',')
alg_assignment = expt_trailer[['userId','loginId','recommenderId']]
alg_assignment.sort_values(by='recommenderId').shape

(510939, 3)

In [4]:
action_alg_data_raw = pd.merge(action_data_raw, alg_assignment, on=['loginId','userId'], how='left')

In [5]:
action_alg_data_raw.dropna(inplace=True)

In [6]:
action_alg_data_raw.groupby("action").count()

,Unnamed: 0,userId,loginId,movieId,tstamp,position,sessionIds,recommenderId
action,,,,,,,,
GoToMovieDetails,889,889,889,889,889,889,889,889
IssueRaised,52,52,52,52,52,52,52,52
MovieDetailsModalClosed,5572,5572,5572,5572,5572,5572,5572,5572
MovieDetailsModalOpened,6024,6024,6024,6024,6024,6024,6024,6024
PlayedFromLaunch,157817,157817,157817,157817,157817,157817,157817,157817
PlayedFromNext,1335,1335,1335,1335,1335,1335,1335,1335
PlayedFromPrevious,181,181,181,181,181,181,181,181
PlayedFromRecommendation,7626,7626,7626,7626,7626,7626,7626,7626
PlayedFromYoutubePlayer,358416,358416,358416,358416,358416,358416,358416,358416
RatedMovie,1209,1209,1209,1209,1209,1209,1209,1209
RecommendationsRefreshed,354,354,354,354,354,354,354,354
TrailerDisliked,901,901,901,901,901,901,901,901
TrailerEnded,23510,23510,23510,23510,23510,23510,23510,23510
TrailerLiked,2096,2096,2096,2096,2096,2096,2096,2096
TrailerModalLaunched,171089,171089,171089,171089,171089,171089,171089,171089
TrailerModalShutdown,55744,55744,55744,55744,55744,55744,55744,55744
TrailerPaused,307063,307063,307063,307063,307063,307063,307063,307063
TrailerUndisliked,86,86,86,86,86,86,86,86
TrailerUnliked,92,92,92,92,92,92,92,92
UnwishlistedMovie,228,228,228,228,228,228,228,228
WishlistedMovie,2825,2825,2825,2825,2825,2825,2825,2825

In [7]:
action_alg_data = action_alg_data_raw[action_alg_data_raw['action'].isin(["TrailerLiked", "TrailerDisliked", "WishlistedMovie","MovieDetailsModalOpened","GoToMovieDetails"])]

In [8]:
action_alg_data.head()

,Unnamed: 0,userId,loginId,movieId,action,tstamp,position,sessionIds,recommenderId
20,20,304211,00bSwKf,139642,MovieDetailsModalOpened,2017-04-29 06:24:17,13,1,FilmReleaseDate
26,26,304211,00bSwKf,136018,MovieDetailsModalOpened,2017-04-29 06:55:56,13,2,FilmReleaseDate
59,59,304211,00bSwKf,165527,MovieDetailsModalOpened,2017-04-29 07:12:17,4,5,FilmReleaseDate
84,84,304211,00bSwKf,113829,MovieDetailsModalOpened,2017-04-29 07:18:21,7,6,FilmReleaseDate
90,90,304211,00bSwKf,127204,MovieDetailsModalOpened,2017-04-29 07:18:48,5,6,FilmReleaseDate

#### Include actions taken on seed movies by appending information about them to the table: ⬇️

In [5]:
all_recs_info = pd.read_csv('../Data/rec_seed_info_raw.csv')

In [26]:
row_0 = all_recs_info.loc[0].copy()

In [133]:
new_df_list = []
new_df_list.append(row_0)

for i in range (0, len(all_recs_info)):
    if (all_recs_info.loc[i]["SeedMovie"]) != new_df_list[len(new_df_list)-1]["SeedMovie"]:
        temp_row = all_recs_info.loc[i].copy()
        temp_row["movieId"]=temp_row["SeedMovie"]
        new_df_list.append(temp_row)
    new_df_list.append(all_recs_info.loc[i])

In [134]:
all_recs_include_seed_info = pd.DataFrame(new_df_list)

In [135]:
all_recs_include_seed_info

,Algorithm,Datetime,SeedMovie,loginId,movieId,sessionIds,userId,avgRating,popularityLastYear,release_date,avgRating_seedmovie,popularityLastYear_seedmovie,release_date_seedmovie,age,age_month,age_seedmovie,age_seedmovie_month
0,PredictedRating,2016-09-12 13:53:04,118985,008C57f,318,1,276159,4.43,7047.0,1994-09-23,3.40,159.0,2014-12-25,8025 days 00:00:00.000000000,267.50,627 days 00:00:00.000000000,20.0
0,PredictedRating,2016-09-12 13:53:04,118985,008C57f,318,1,276159,4.43,7047.0,1994-09-23,3.40,159.0,2014-12-25,8025 days 00:00:00.000000000,267.50,627 days 00:00:00.000000000,20.0
1,PredictedRating,2016-09-12 13:53:04,118985,008C57f,93721,1,276159,3.95,229.0,2011-06-15,3.40,159.0,2014-12-25,1916 days 00:00:00.000000000,63.87,627 days 00:00:00.000000000,20.0
2,PredictedRating,2016-09-12 13:53:04,118985,008C57f,148626,1,276159,4.01,1744.0,2015-12-12,3.40,159.0,2014-12-25,275 days 00:00:00.000000000,9.17,627 days 00:00:00.000000000,20.0
3,PredictedRating,2016-09-12 13:53:04,118985,008C57f,2966,1,276159,3.93,94.0,1999-10-15,3.40,159.0,2014-12-25,6177 days 00:00:00.000000000,205.90,627 days 00:00:00.000000000,20.0
4,PredictedRating,2016-09-12 13:53:04,118985,008C57f,81845,1,276159,3.93,2032.0,2010-11-26,3.40,159.0,2014-12-25,2117 days 00:00:00.000000000,70.57,627 days 00:00:00.000000000,20.0
5,PredictedRating,2016-09-12 13:53:04,118985,008C57f,142488,1,276159,4.08,1168.0,2015-11-06,3.40,159.0,2014-12-25,311 days 00:00:00.000000000,10.37,627 days 00:00:00.000000000,20.0
6,PredictedRating,2016-09-12 13:53:04,118985,008C57f,106100,1,276159,3.91,1390.0,2013-10-10,3.40,159.0,2014-12-25,1068 days 00:00:00.000000000,35.60,627 days 00:00:00.000000000,20.0
7,PredictedRating,2016-09-12 13:53:04,118985,008C57f,106889,1,276159,3.97,41.0,2013-12-31,3.40,159.0,2014-12-25,986 days 00:00:00.000000000,32.87,627 days 00:00:00.000000000,20.0
8,PredictedRating,2016-09-12 13:53:04,118985,008C57f,678,1,276159,4.07,18.0,1994-01-24,3.40,159.0,2014-12-25,8267 days 00:00:00.000000000,275.57,627 days 00:00:00.000000000,20.0
9,PredictedRating,2016-09-12 13:53:04,118985,008C57f,4995,1,276159,3.96,2918.0,2002-01-04,3.40,159.0,2014-12-25,5365 days 00:00:00.000000000,178.83,627 days 00:00:00.000000000,20.0
10,PredictedRating,2016-09-12 13:53:04,118985,008C57f,2725,1,276159,3.57,6.0,1999-07-30,3.40,159.0,2014-12-25,6254 days 00:00:00.000000000,208.47,627 days 00:00:00.000000000,20.0
11,PredictedRating,2016-09-12 13:53:04,118985,008C57f,96488,1,276159,3.97,166.0,2012-07-27,3.40,159.0,2014-12-25,1508 days 00:00:00.000000000,50.27,627 days 00:00:00.000000000,20.0
12,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,34162,1,305068,3.42,41.0,2012-11-16,3.45,1067.0,2005-07-15,1835 days 00:00:00.000000000,61.17,4516 days 00:00:00.000000000,150.0
12,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,89898,1,305068,3.42,41.0,2012-11-16,3.45,1067.0,2005-07-15,1835 days 00:00:00.000000000,61.17,4516 days 00:00:00.000000000,150.0
13,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,87785,1,305068,3.07,33.0,2010-08-27,3.45,1067.0,2005-07-15,2647 days 00:00:00.000000000,88.23,4516 days 00:00:00.000000000,150.0
14,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,86884,1,305068,3.73,33.0,2012-03-16,3.45,1067.0,2005-07-15,2080 days 00:00:00.000000000,69.33,4516 days 00:00:00.000000000,150.0
15,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,81804,1,305068,3.46,37.0,2010-10-29,3.45,1067.0,2005-07-15,2584 days 00:00:00.000000000,86.13,4516 days 00:00:00.000000000,150.0
16,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,4427,1,305068,4.04,36.0,1968-10-30,3.45,1067.0,2005-07-15,17923 days 00:00:00.000000000,597.43,4516 days 00:00:00.000000000,150.0
17,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,4444,1,305068,3.70,35.0,1972-12-30,3.45,1067.0,2005-07-15,16401 days 00:00:00.000000000,546.70,4516 days 00:00:00.000000000,150.0
18,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,3952,1,305068,3.61,26.0,2000-10-13,3.45,1067.0,2005-07-15,6252 days 00:00:00.000000000,208.40,4516 days 00:00:00.000000000,150.0
19,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,81191,1,305068,3.62,29.0,2010-10-08,3.45,1067.0,2005-07-15,2605 days 00:00:00.000000000,86.83,4516 days 00:00:00.000000000,150.0
20,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,4474,1,305068,3.17,32.0,1988-12-21,3.45,1067.0,2005-07-15,10566 days 00:00:00.000000000,352.20,4516 days 00:00:00.000000000,150.0
21,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,538,1,305068,3.70,28.0,1993-01-01,3.45,1067.0,2005-07-15,9094 days 00:00:00.000000000,303.13,4516 days 00:00:00.000000000,150.0
22,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,80939,1,305068,3.52,28.0,2010-10-15,3.45,1067.0,2005-07-15,2598 days 00:00:00.000000000,86.60,4516 days 00:00:00.000000000,150.0
23,ShuffledTopPicks,2017-11-25 12:21:19,34162,009NNgE,1057,1,305068,3.43,30.0,1996-12-06,3.45,1067.0,2005-07-15,7659 days 00:00:00.000000000,255.30,4516 days 00:00:00.000000000,150.0
24,ShuffledTopPicks,2017-11-25 12:24:10,4018,009NNgE,4018,2,305068,3.46,37.0,2010-10-29,3.12,1001.0,2000-12-15,2584 days 00:00:00.000000000,86.13,6189 days 00:00:00.000000000,206.0
24,ShuffledTopPicks,2017-11-25 12:24:10,4018,009NNgE,81804,2,305068,3.46,37.0,2010-10-29,3.12,1001.0,2000-12-15,2584 days 00:00:00.000000000,86.13,6189 days 00:00:00.000000000,206.0
25,ShuffledTopPicks,2017-11-25 12:24:10,4018,009NNgE,87785,2,305068,3.07,33.0,2010-08-27,3.12,1001.0,2000-12-15,2647 days 00:00:00.000000000,88.23,6189 days 00:00:00.000000000,206.0
26,ShuffledTopPicks,2017-11-25 12:24:10,4018,009NNgE,1057,2,305068,3.43,30.0,1996-12-06,3.12,1001.0,2000-12-15,7659 days 00:00:00.000000000,255.30,6189 days 00:00:00.000000000,206.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779008,FilmReleaseDate,2016-10-15 19:19:56,142488,zZxjv9Q,118930,1,293951,3.93,51.0,2014-12-05,4.08,1168.0,2015-11-06,680 days 00:00:00.000000000,22.67,344 days 00:00:00.000000000,11.0
1779009,FilmReleaseDate,2016-10-15 19:19:56,142488,zZxjv9Q,116797,1,293951,4.02,3372.0,2014-11-28,4.08,1168.0,2015-11-06,687 days 00:00:00.000000000,22.90,344 days 00:00:00.000000000,11.0
1779010,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,64620,1,208495,3.96,2918.0,2002-01-04,3.78,185.0,2008-12-05,5353 days 00:00:00.000000000,178.43,2826 days 00:00:00.000000000,94.0
1779010,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,4995,1,208495,3.96,2918.0,2002-01-04,3.78,185.0,2008-12-05,5353 days 00:00:00.000000000,178.43,2826 days 00:00:00.000000000,94.0
1779011,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,1203,1,208495,4.24,1064.0,1957-04-13,3.78,185.0,2008-12-05,21690 days 00:00:00.000000000,723.00,2826 days 00:00:00.000000000,94.0
1779012,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,48738,1,208495,3.85,440.0,2006-09-27,3.78,185.0,2008-12-05,3626 days 00:00:00.000000000,120.87,2826 days 00:00:00.000000000,94.0
1779013,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,5989,1,208495,3.91,3061.0,2002-12-25,3.78,185.0,2008-12-05,4998 days 00:00:00.000000000,166.60,2826 days 00:00:00.000000000,94.0
1779014,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,85774,1,208495,3.98,157.0,2011-08-12,3.78,185.0,2008-12-05,1846 days 00:00:00.000000000,61.53,2826 days 00:00:00.000000000,94.0
1779015,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,131724,1,208495,4.11,114.0,2015-02-08,3.78,185.0,2008-12-05,570 days 00:00:00.000000000,19.00,2826 days 00:00:00.000000000,94.0
1779016,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,49530,1,208495,3.86,1340.0,2006-12-08,3.78,185.0,2008-12-05,3554 days 00:00:00.000000000,118.47,2826 days 00:00:00.000000000,94.0
1779017,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,2194,1,208495,3.87,553.0,1987-06-03,3.78,185.0,2008-12-05,10682 days 00:00:00.000000000,356.07,2826 days 00:00:00.000000000,94.0
1779018,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,2268,1,208495,3.81,694.0,1992-12-11,3.78,185.0,2008-12-05,8664 days 00:00:00.000000000,288.80,2826 days 00:00:00.000000000,94.0
1779019,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,44555,1,208495,4.20,749.0,2007-02-09,3.78,185.0,2008-12-05,3491 days 00:00:00.000000000,116.37,2826 days 00:00:00.000000000,94.0
1779020,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,1267,1,208495,4.09,142.0,1962-10-24,3.78,185.0,2008-12-05,19670 days 00:00:00.000000000,655.67,2826 days 00:00:00.000000000,94.0
1779021,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,116797,1,208495,4.02,3372.0,2014-11-28,3.78,185.0,2008-12-05,642 days 00:00:00.000000000,21.40,2826 days 00:00:00.000000000,94.0
1779022,PredictedRating,2016-08-31 11:08:02,64620,ZzYjRmM,109687,1,208495,3.80,31.0,2014-03-05,3.78,185.0,2008-12-05,910 days 00:00:00.000000000,30.33,2826 days 00:00:00.000000000,94.0
1779023,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,8784,1,312276,3.77,1765.0,2016-12-01,3.76,677.0,2004-07-30,288 days 00:00:00.000000000,9.60,4795 days 00:00:00.000000000,159.0
1779023,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,164909,1,312276,3.77,1765.0,2016-12-01,3.76,677.0,2004-07-30,288 days 00:00:00.000000000,9.60,4795 days 00:00:00.000000000,159.0
1779024,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,165549,1,312276,3.83,917.0,2016-11-18,3.76,677.0,2004-07-30,301 days 00:00:00.000000000,10.03,4795 days 00:00:00.000000000,159.0
1779025,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,161922,1,312276,3.72,542.0,2016-09-30,3.76,677.0,2004-07-30,350 days 00:00:00.000000000,11.67,4795 days 00:00:00.000000000,159.0
1779026,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,158966,1,312276,3.94,841.0,2016-07-08,3.76,677.0,2004-07-30,434 days 00:00:00.000000000,14.47,4795 days 00:00:00.000000000,159.0
1779027,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,159717,1,312276,3.74,200.0,2016-06-24,3.76,677.0,2004-07-30,448 days 00:00:00.000000000,14.93,4795 days 00:00:00.000000000,159.0
1779028,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,156387,1,312276,3.91,362.0,2016-04-22,3.76,677.0,2004-07-30,511 days 00:00:00.000000000,17.03,4795 days 00:00:00.000000000,159.0
1779029,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,142222,1,312276,3.58,204.0,2016-04-08,3.76,677.0,2004-07-30,525 days 00:00:00.000000000,17.50,4795 days 00:00:00.000000000,159.0
1779030,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,157268,1,312276,3.31,66.0,2016-03-13,3.76,677.0,2004-07-30,551 days 00:00:00.000000000,18.37,4795 days 00:00:00.000000000,159.0
1779031,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,152970,1,312276,3.98,535.0,2016-01-22,3.76,677.0,2004-07-30,602 days 00:00:00.000000000,20.07,4795 days 00:00:00.000000000,159.0
1779032,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,140174,1,312276,3.98,847.0,2015-10-14,3.76,677.0,2004-07-30,702 days 00:00:00.000000000,23.40,4795 days 00:00:00.000000000,159.0
1779033,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,127206,1,312276,3.44,18.0,2015-01-26,3.76,677.0,2004-07-30,963 days 00:00:00.000000000,32.10,4795 days 00:00:00.000000000,159.0
1779034,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,127202,1,312276,3.87,358.0,2015-01-25,3.76,677.0,2004-07-30,964 days 00:00:00.000000000,32.13,4795 days 00:00:00.000000000,159.0
1779035,FilmReleaseDate,2017-09-15 22:04:24,8784,zZZisC6,127198,1,312276,3.65,172.0,2015-01-24,3.76,677.0,2004-07-30,965 days 00:00:00.000000000,32.17,4795 days 00:00:00.000000000,159.0

#### Complete appending information about seed movies to the table ⤴️

#### Load RC trailers & alg assignment

In [9]:
rec_played_alg = pd.read_csv("../Clean_Data/rec_played_alg.csv")
rec_played_alg.drop("Unnamed: 0",axis=1,inplace=True)

In [10]:
rec_played_alg.dropna(inplace=True)

In [39]:
rec_content_include_seed = pd.merge(rec_played_alg,all_recs_include_seed_info,on=["loginId","sessionIds","movieId"],how="left")

In [99]:
rec_content_include_seed.dropna(inplace=True)

In [100]:
rec_interactions = pd.merge(rec_content_include_seed,action_alg_data,on=["loginId","sessionIds","movieId"],how="left")
rec_interactions.drop(["position_y","recommenderId_y"], axis=1, inplace=True)

In [101]:
rec_interactions.count()

userId_x                        8241
loginId                         8241
movieId                         8241
action_x                        8241
tstamp_x                        8241
position_x                      8241
sessionIds                      8241
recommenderId_x                 8241
Algorithm                       8241
Datetime                        8241
SeedMovie                       8241
userId_y                        8241
avgRating                       8241
popularityLastYear              8241
release_date                    8241
avgRating_seedmovie             8241
popularityLastYear_seedmovie    8241
release_date_seedmovie          8241
age                             8241
age_month                       8241
age_seedmovie                   8241
age_seedmovie_month             8241
Unnamed: 0                      2188
userId                          2188
action_y                        2188
tstamp_y                        2188
dtype: int64

In [102]:
rec_interactions['isLiked'] = False
rec_interactions['isDisliked'] = False
rec_interactions['isWishlisted'] = False

In [103]:
for index, row in rec_interactions.iterrows():
    if row['action_y']=="TrailerLiked":
        #row.['isLiked']=True
        #row.isLiked=True

        rec_interactions.loc[index,'isLiked']=True
    elif row['action_y']=="TrailerDisliked":
        #row['isDisliked']==True
        rec_interactions.loc[index,'isDisliked']=True
        #row.isLiked=True
    elif row['action_y']=="WishlistedMovie":
        if (row['tstamp_y']>row['tstamp_x']):
            #row['isWishlisted']==True
            rec_interactions.loc[index,'isWishlisted']=True
            #row.isLiked=True

In [46]:
rec_interactions.loc[rec_interactions.action_y=="TrailerLiked",'isLiked']=True
rec_interactions.loc[rec_interactions.action_y=="TrailerDisliked",'isDisliked']=True
rec_interactions.loc[rec_interactions.action_y=="WishlistedMovie",'isWishlisted']=True

In [105]:
rec_interactions.drop(['Unnamed: 0','userId_y','Algorithm','age','age_seedmovie'],axis=1,inplace=True)

In [108]:
rec_interactions.to_csv('../Clean_Data/action_frequency_5_02.csv')

### Include WatchMoreThanHalf

In [109]:
watch = pd.read_csv('../Clean_Data/log_trailer_watch.csv')

# Exclude movielens users
mlusers = [32451,49002,49253,50540,51234,51714,65817,66644,68903,70023,70026,92721,92723,95195,96279,96483,96691,97397,104218,113699,114092,114844,122798,124450,124790,125283,125431,127628,127979,129299,130353,132131,132145,132637,132726,132728,132871,133047,134070,134088,134143,134235,134342,134349,134372,134373,134393,134484,134496,134498,134504,134533,135260,135670,136346,136505,136995,137096,137331,137372,138083,138089,138090,138108,141799,142115,143473,149815,151709,151982,166008,173637,176970,183038,183567,197881,202657,207221,221192,221515,225510,233659,233985,237287,237332,238576,238876,240312,242238,242683,243010,243445,245696,246018,246058,246587,246828,248583,251610,251922,252238,252534,253066,253866,253869,257628,257629,257756,258553,258554,258555,258556,258557,258558,258559,258560,258561,258562,258563,258564,258565,259056,260701,264178,266542,268253,269945,286014,287206,292397,301040,304542,313322,316070,317416,318334]

watch_small = watch[watch['tstamp']<"2018-01-17 01:59:42"]

watch_noml = watch_small[~watch_small.userId.isin(mlusers)]
watch_noml = watch_noml.drop(['youtubeTrailerId'],axis=1).copy()

In [110]:
watch_noml_small = watch_noml[watch_noml['percentWatched']<=100].copy()
watch_noml_small.sort_values('percentWatched',ascending=False, inplace=True)
watch_noml_small.sort_values(by=['loginId','movieId'],inplace=True)

In [113]:
watch_nodup = watch_noml_small.drop_duplicates(subset=["loginId","movieId"], keep="first").copy()

,userId,loginId,movieId,percentWatched,positionInList,tstamp
116436,276159,008C57f,118985,90,0,2016-09-12 13:55:20
588111,305068,009NNgE,34162,45,0,2017-11-25 12:22:32
556148,314354,009PCM1,1222,90,0,2017-10-29 17:22:16
589454,304970,00AmPNC,133419,60,0,2017-11-26 03:46:48
70845,233888,00Et4vt,1466,30,0,2016-07-22 05:09:54

In [116]:
watch_nodup.rename(columns={"positionInList":"position"},inplace=True)

#### Combine the table with percentWatched with rec_content_include_seed that has other actions

In [120]:
rec_content_include_seed.rename(columns={"userId_x":"userId"},inplace=True)

In [121]:
rec_interactions_with_watch = pd.merge(rec_content_include_seed,watch_nodup,on=["loginId","userId","movieId","position"],how="left")

In [126]:
rec_interactions_with_watch['watchMoreThanHalf']=False

In [127]:
rec_interactions_with_watch.loc[rec_interactions_with_watch.percentWatched>=50,'watchMoreThanHalf']=True

In [128]:
rec_interactions_with_watch.groupby("watchMoreThanHalf").count()

,userId,loginId,movieId,action,tstamp_x,position,sessionIds,recommenderId,Algorithm,Datetime,...,release_date,avgRating_seedmovie,popularityLastYear_seedmovie,release_date_seedmovie,age,age_month,age_seedmovie,age_seedmovie_month,percentWatched,tstamp_y
watchMoreThanHalf,,,,,,,,,,,,,,,,,,,,,
False,4203,4203,4203,4203,4203,4203,4203,4203,4203,4203,...,4203,4203,4203,4203,4203,4203,4203,4203,1430,1430
True,3296,3296,3296,3296,3296,3296,3296,3296,3296,3296,...,3296,3296,3296,3296,3296,3296,3296,3296,3296,3296

In [129]:
rec_interactions_with_watch.to_csv('../Clean_Data/action_watchmorethanhalf_5_02.csv')